sudo: required
language: node_js
node_js:
  - "9"
cache:
  yarn: true
script: yarn qa
before_deploy:
  - sudo python -m pip install awscli==1.14.7
deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh esc_test
    on:
      branch: develop
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh esc_prod
    on:
      branch: master
