sudo: required
language: node_js
node_js:
  - "9"
cache:
  yarn: true
script: yarn qa && GATSBY_DATA_TARGET=esc yarn build
before_deploy:
  - sudo python -m pip install awscli==1.14.7
deploy:
  # deploy to the staging environment
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh esc_test
    on:
      branch: master
  # deploy to production
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh esc_prod
    on:
      branch: deploy
