backend:
  name: github
  repo: buz-zard/cc-web
  branch: feat/netlify

media_folder: static/assets

publish_mode: editorial_workflow

collections:
  - label: Service
    name: service
    folder: src/content/service
    create: true
    fields:
      - { name: title, label: Title EN }
      - { name: title_sv, label: Title SV }
      - { name: order, label: Order, widget: number, min: 1, default: 1 }
